apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: cloudops@optimizely.com
    privateKeySecretRef:
      name: argocd-server-tls
    solvers:
      - http01:
          ingress:
            class: azure/application-gateway
