apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: saas-portal-prod
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: site-reliability-engineer
  namespace: saas-portal-prod
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
