apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: site-reliability-engineer
  namespace: saas-portal-dev
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developer
  namespace: saas-portal-dev
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]