apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-accounts
  namespace: argo
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  accounts.administrator: login,apiKey
  accounts.maintainer: login,apiKey
  accounts.reader: login,apiKey
  timeout.reconciliation: 15s
